const studentsData = [
    {    classRoll: 2023, registrationNo: 20203652394, name: 'ARIFA AKTER SHORNA', gender: 'Female', department: 'IIT', hallName: 'Bangamata Begum Fazilatunnessa Mujib' },
    {    classRoll: 2024, registrationNo: 20203652395, name: 'IBNAT-NUR-SHRABONY', gender: 'Female', department: 'IIT', hallName: 'Bangamata Begum Fazilatunnessa Mujib' },
    {    classRoll: 2025, registrationNo: 20203652396, name: 'NOUSHIN ULFAT SHUKANNYA', gender: 'Female', department: 'IIT', hallName: 'Bangamata Begum Fazilatunnessa Mujib' },
    {    classRoll: 2026, registrationNo: 20203652397, name: 'JOYA BISWAS', gender: 'Female', department: 'IIT', hallName: 'Bangamata Begum Fazilatunnessa Mujib' },
    {    classRoll: 2027, registrationNo: 20203652398, name: 'TASFIA ISRAT', gender: 'Female', department: 'IIT', hallName: 'Begum Sufia Kamal' },
    {    classRoll: 2028, registrationNo: 20203652399, name: 'ZEBA TASNIA', gender: 'Female', department: 'IIT', hallName: 'Begum Sufia Kamal' },
    {    classRoll: 2029, registrationNo: 20203652400, name: 'FAHMIDA ISLAM MEEM', gender: 'Female', department: 'IIT', hallName: 'Begum Sufia Kamal' },
    {    classRoll: 2030, registrationNo: 20203652401, name: 'SUMAIAY SIDDIKA', gender: 'Female', department: 'IIT', hallName: 'Begum Sufia Kamal' },
    {    classRoll: 2031, registrationNo: 20203652402, name: 'TAHSHINA TABASSUM', gender: 'Female', department: 'IIT', hallName: 'Jahanara Imam' },
    {    classRoll: 2032, registrationNo: 20203652403, name: 'SANJIDA SIDDIK TOMA', gender: 'Female', department: 'IIT', hallName: 'Jahanara Imam' },
    {    classRoll: 2033, registrationNo: 20203652404, name: 'SHARAH SOFIA', gender: 'Female', department: 'IIT', hallName: 'Jahanara Imam' },
    {    classRoll: 2034, registrationNo: 20203652405, name: 'SADIA MAHFUZ', gender: 'Female', department: 'IIT', hallName: 'Pritilata' },
    {    classRoll: 2035, registrationNo: 20203652406, name: 'FATHIMA BINTHE MUHAMMED', gender: 'Female', department: 'IIT', hallName: 'Pritilata' },
    {    classRoll: 2036, registrationNo: 20203652407, name: 'SANZIDA AKTER', gender: 'Female', department: 'IIT', hallName: 'Pritilata' },
    {    classRoll: 2037, registrationNo: 20203652408, name: 'NAFISA AHMED', gender: 'Female', department: 'IIT', hallName: 'Pritilata' },
    {    classRoll: 2038, registrationNo: 20203652409, name: 'RUTABAN JANIA', gender: 'Female', department: 'IIT', hallName: 'Begum Khaleda Zia' },
    {    classRoll: 2039, registrationNo: 20203652410, name: 'FAHMIDA SULTANA', gender: 'Female', department: 'IIT', hallName: 'Begum Khaleda Zia' },
    {    classRoll: 2040, registrationNo: 20203652411, name: 'MST. SONALI AKTER SWARNA', gender: 'Female', department: 'IIT', hallName: 'Begum Khaleda Zia' },
    {    classRoll: 2041, registrationNo: 20203652412, name: 'MIM KHATUN', gender: 'Female', department: 'IIT', hallName: 'Begum Khaleda Zia' },
    {    classRoll: 2042, registrationNo: 20203652413, name: 'RIVA AKTER', gender: 'Female', department: 'IIT', hallName: 'Sheikh Hasina' },
    {    classRoll: 2043, registrationNo: 20203652414, name: 'MST. AMINA KHATUN BOBY', gender: 'Female', department: 'IIT', hallName: 'Sheikh Hasina' },
    {    classRoll: 2044, registrationNo: 20203652415, name: 'KOUSHIKI DEVI AGARWALLA', gender: 'Female', department: 'IIT', hallName: 'Sheikh Hasina' },
    {    classRoll: 2045, registrationNo: 20203652416, name: 'MOSAMMAT ROJINA KHATUN', gender: 'Female', department: 'IIT', hallName: 'Sheikh Hasina' },
    {    classRoll: 2046, registrationNo: 20203652417, name: 'SUMAIA ISLAM SORNA', gender: 'Female', department: 'IIT', hallName: 'Sheikh Hasina' },
    {    classRoll: 2047, registrationNo: 20203652418, name: 'AMINA BEGUM', gender: 'Female', department: 'IIT', hallName: 'Sheikh Hasina' },
    {    classRoll: 2048, registrationNo: 20203652419, name: 'TANDRA BISWAS', gender: 'Female', department: 'IIT', hallName: 'Nawab Faizunnesa' },
    {    classRoll: 2049, registrationNo: 20203652420, name: 'UPAMA TALUKDER', gender: 'Female', department: 'IIT', hallName: 'Nawab Faizunnesa' },
    {    classRoll: 2050, registrationNo: 20203652421, name: 'RAMISA FARIHA', gender: 'Female', department: 'IIT', hallName: 'Nawab Faizunnesa' },
    {    classRoll: 2051, registrationNo: 20203652422,  name: 'FATEMA - TUZ - JOHURA PRAPTY', gender: 'Female', department: 'IIT', hallName: 'Nawab Faizunnesa', remark: 'Ward' },
    {   classRoll: 2052, registrationNo: 20203652423, name: 'ANOY BHOWMICK', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
    {   classRoll: 2053, registrationNo: 20203652424, name: 'ASHFAKUL ISLAM BHUIYAN', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
    {   classRoll: 2054, registrationNo: 20203652425, name: 'Z.M. MAHBUBUR RAHMAN RAFI', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
    {   classRoll: 2055, registrationNo: 20203652426, name: 'NAYON KARMOKER', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
    {  classRoll: 2056, registrationNo: 20203652427, name: 'MD. RAKHIBUL HASAN', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
  {   classRoll: 2057, registrationNo: 20203652428, name: 'SHRAWMAN MAJUMDER RUDRA', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
  {   classRoll: 2058, registrationNo: 20203652429, name: 'ANIK KAISAR', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
  {   classRoll: 2059, registrationNo: 20203652430, name: 'MD.MAHATAB HOSSAIN TAMAL', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain' },
  {   classRoll: 2060, registrationNo: 20203652431, name: 'RASEDUL MANNAN', gender: 'Male', department: 'IIT', hallName: 'Mowlana Bashani' },
  {   classRoll: 2061, registrationNo: 20203652432, name: 'UMIT SAHA', gender: 'Male', department: 'IIT', hallName: 'Mowlana Bashani' },
  {   classRoll: 2062, registrationNo: 20203652433, name: 'SHEIKH RAIHAN AKTER', gender: 'Male', department: 'IIT', hallName: 'Mowlana Bashani' },
  {   classRoll: 2063, registrationNo: 20203652434, name: 'MD. SOHEL RANA', gender: 'Male', department: 'IIT', hallName: 'Shaheed Salam-Barkat' },
  {   classRoll: 2064, registrationNo: 20203652435, name: 'MD. IMRANUR RAHMAN', gender: 'Male', department: 'IIT', hallName: 'Shaheed Salam-Barkat' },
  {   classRoll: 2065, registrationNo: 20203652436, name: 'MD. YASHRIF ARIFIN SWOCCHO', gender: 'Male', department: 'IIT', hallName: 'Shaheed Salam-Barkat' },
  {   classRoll: 2066, registrationNo: 20203652437, name: 'NAZMUL NAHIAN SAGOR', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2067, registrationNo: 20203652438, name: 'SAIF MOHAMMED OMER', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2068, registrationNo: 20203652439, name: 'MANSIBUR RAHMAN SADH', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2069, registrationNo: 20203652440, name: 'MD. APU', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2070, registrationNo: 20203652441, name: 'RATUL MANDAL', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2071, registrationNo: 20203652442, name: 'RIASAD ALAM', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2072, registrationNo: 20203652443, name: 'ARAF MIAD', gender: 'Male', department: 'IIT', hallName: 'A F M Kamaluddin' },
  {   classRoll: 2073, registrationNo: 20203652444, name: 'RAHAT KHAN', gender: 'Male', department: 'IIT', hallName: 'A F M Kamaluddin' },
  {   classRoll: 2074, registrationNo: 20203652445, name: 'MD. ASIF MAZUMDER SHAMIM', gender: 'Male', department: 'IIT', hallName: 'A F M Kamaluddin' },
  {   classRoll: 2075, registrationNo: 20203652446, name: 'MD. ASHRAFUL ISLAM', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman' },
  {   classRoll: 2076, registrationNo: 20203652447, name: 'MAHMODOL HASSAN MONNA', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman' },
  {   classRoll: 2077, registrationNo: 20203652448, name: 'MD. MUSTAFIZUR RAHMAN NAHID', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman' },
  {   classRoll: 2078, registrationNo: 20203652449, name: 'JAHID HOSSAIN', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman' },
  {   classRoll: 2079, registrationNo: 20203652450, name: 'MD. ARMANUL ALAM', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman' },
  {   classRoll: 2080, registrationNo: 20203652451, name: 'MEHEDI HASAN ANIK', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman',   },
  {   classRoll: 2081, registrationNo: 20203652452, name: 'MD. NAFIS HASNAT', gender: 'Male', department: 'IIT', hallName: 'Shaheed Rafiq-Jabbar' },
  {   classRoll: 2082, registrationNo: 20203652453, name: 'MD.RAFIUL HOQUE', gender: 'Male', department: 'IIT', hallName: 'Shaheed Salam-Barkat' },
  {   classRoll: 2083, registrationNo: 20203652454, name: 'MD. SAZZAD HOSSAIN BHUIYAN', gender: 'Male', department: 'IIT', hallName: 'Mir Mosharraf Hossain'},
  {   classRoll: 2084, registrationNo: 20203652455, name: 'MOHAMMAD SHAMSE KADIR KHAN', gender: 'Male', department: 'IIT', hallName: 'Bangabandhu Sheikh Mujibur Rahman' },
  {   classRoll: 2085, registrationNo: 20203652456, name: 'ANTOR KUMAR BISWAS', gender: 'Male', department: 'IIT', hallName: 'Mowlana Bashani'  }
  ];
  
  export default studentsData;
 